import type { TemplateSeed } from "./templates.types";

export const templateSeeds: TemplateSeed[] = [
  {
    id: "summer-square",
    slug: "summer-square",
    name: "夏天毕业方版",
    categoryCode: "graduation",
    categoryName: "毕业纪念",
    summary: "先把毕业典礼、班级合照和老师笑脸收进一本温柔的小书里。",
    description: "适合从毕业典礼开始讲起，把老师寄语、班级笑脸和最后一个夏天的回忆放在一起。",
    themeLabel: "夏日清新",
    badgeText: "推荐起步款",
    photoSuggestionText: "建议准备 8-28 张照片",
    storyHighlights: ["毕业典礼", "老师寄语", "班级合照"],
    suitableScenes: ["幼儿园毕业照", "全班合照", "老师合影"],
    pageCount: 20,
    minPhotos: 8,
    priceInCents: 12800,
    coverTone: "#F7C96F",
    accentTone: "#77B979",
    coverImage: "/assets/templates/summer-square/cover.jpg",
    previewImages: [
      "/assets/templates/summer-square/cover.jpg",
      "/assets/templates/summer-square/page-1.jpg",
      "/assets/templates/summer-square/page-2.jpg",
      "/assets/templates/summer-square/page-3.jpg"
    ],
    isFeatured: true
  },
  {
    id: "graduation-memory",
    slug: "graduation-memory",
    name: "毕业纪念册",
    categoryCode: "graduation",
    categoryName: "毕业纪念",
    summary: "把上台、合影和老师送别的话，整理成更正式的一本毕业纪念册。",
    description: "更适合毕业仪式感强一点的班级，把上台、送花、老师寄语和整班合照都留得完整一些。",
    themeLabel: "毕业典礼",
    badgeText: "仪式感更多",
    photoSuggestionText: "建议准备 10-32 张照片",
    storyHighlights: ["上台时刻", "老师送花", "全班大合照"],
    suitableScenes: ["毕业典礼", "班级送别", "舞台瞬间"],
    pageCount: 21,
    minPhotos: 10,
    priceInCents: 13800,
    coverTone: "#F7B766",
    accentTone: "#83C7D8",
    coverImage: "/assets/templates/graduation-memory/cover.jpg",
    previewImages: [
      "/assets/templates/graduation-memory/cover.jpg",
      "/assets/templates/graduation-memory/page-1.jpg",
      "/assets/templates/graduation-memory/page-2.jpg",
      "/assets/templates/graduation-memory/page-3.jpg"
    ]
  },
  {
    id: "growth-album",
    slug: "growth-album",
    name: "幼儿园成长相册",
    categoryCode: "growth",
    categoryName: "成长记录",
    summary: "把日常课堂、活动笑脸和一点点长大的瞬间，讲成一本成长故事。",
    description: "更适合记录日常课堂、春游活动和慢慢长大的小表情，整体会更轻快、更像成长故事。",
    themeLabel: "成长故事",
    badgeText: "日常感更强",
    photoSuggestionText: "建议准备 10-36 张照片",
    storyHighlights: ["日常课堂", "活动笑脸", "成长小片段"],
    suitableScenes: ["成长记录", "校园日常", "活动留念"],
    pageCount: 25,
    minPhotos: 10,
    priceInCents: 10800,
    coverTone: "#B8DDA4",
    accentTone: "#F2A08A",
    coverImage: "/assets/templates/growth-album/cover.jpg",
    previewImages: [
      "/assets/templates/growth-album/cover.jpg",
      "/assets/templates/growth-album/page-1.jpg",
      "/assets/templates/growth-album/page-2.jpg",
      "/assets/templates/growth-album/page-3.jpg"
    ]
  },
  {
    id: "class-square",
    slug: "class-square",
    name: "班级毕业方版",
    categoryCode: "classroom",
    categoryName: "班级活动",
    summary: "适合把全班活动、集体照和教室里的热闹时刻收在一起。",
    description: "更适合班级活动照和整班合影，打开时会先看到热闹的集体氛围，再慢慢翻到每个孩子的笑脸。",
    themeLabel: "班级合辑",
    badgeText: "全班氛围款",
    photoSuggestionText: "建议准备 12-40 张照片",
    storyHighlights: ["班级活动", "集体合照", "教室日常"],
    suitableScenes: ["班级纪念", "节日活动", "教室生活"],
    pageCount: 20,
    minPhotos: 12,
    priceInCents: 15800,
    coverTone: "#8ECDE7",
    accentTone: "#F6B16B",
    coverImage: "/assets/templates/class-square/cover.jpg",
    previewImages: [
      "/assets/templates/class-square/cover.jpg",
      "/assets/templates/class-square/page-1.jpg",
      "/assets/templates/class-square/page-2.jpg",
      "/assets/templates/class-square/page-3.jpg"
    ]
  },
  {
    id: "illustration-square",
    slug: "illustration-square",
    name: "手绘插画方版",
    categoryCode: "growth",
    categoryName: "成长记录",
    summary: "更像一本温柔的童年绘本，适合把单人笑脸和小动作留得更可爱。",
    description: "适合喜欢温柔一点、童趣一点风格的家长，整本会更像一本陪伴孩子长大的小绘本。",
    themeLabel: "童趣绘本",
    badgeText: "温柔可爱",
    photoSuggestionText: "建议准备 10-30 张照片",
    storyHighlights: ["单人笑脸", "童趣动作", "温柔寄语"],
    suitableScenes: ["成长纪念", "单人写真", "日常记录"],
    pageCount: 19,
    minPhotos: 10,
    priceInCents: 14800,
    coverTone: "#F9C6A2",
    accentTone: "#8CCB9B",
    coverImage: "/assets/templates/illustration-square/cover.jpg",
    previewImages: [
      "/assets/templates/illustration-square/cover.jpg",
      "/assets/templates/illustration-square/page-1.jpg",
      "/assets/templates/illustration-square/page-2.jpg",
      "/assets/templates/illustration-square/page-3.jpg"
    ]
  },
  {
    id: "graduation-landscape",
    slug: "graduation-landscape",
    name: "毕业季横版",
    categoryCode: "graduation",
    categoryName: "毕业纪念",
    summary: "更适合横向大合照和舞台活动，把热闹场面留得更完整。",
    description: "适合横向大合照、活动抓拍和舞台场景，翻页时更容易先看到热闹的整体氛围。",
    themeLabel: "活动纪实",
    badgeText: "合照友好",
    photoSuggestionText: "建议准备 12-34 张照片",
    storyHighlights: ["大合照", "舞台活动", "热闹瞬间"],
    suitableScenes: ["毕业活动", "舞台演出", "大场景合照"],
    pageCount: 19,
    minPhotos: 12,
    priceInCents: 16800,
    coverTone: "#B7DDF4",
    accentTone: "#F8C36B",
    coverImage: "/assets/templates/graduation-landscape/cover.jpg",
    previewImages: [
      "/assets/templates/graduation-landscape/cover.jpg",
      "/assets/templates/graduation-landscape/page-1.jpg",
      "/assets/templates/graduation-landscape/page-2.jpg",
      "/assets/templates/graduation-landscape/page-3.jpg"
    ]
  },
  {
    id: "graduation-portrait",
    slug: "graduation-portrait",
    name: "毕业季竖版",
    categoryCode: "graduation",
    categoryName: "毕业纪念",
    summary: "更适合单人竖图和成长小片段，把孩子的笑脸留得更近一些。",
    description: "适合单人竖幅照片、成长细节和安静一点的毕业纪念风格，整本会更聚焦孩子自己的笑脸。",
    themeLabel: "轻量成长",
    badgeText: "单人更出彩",
    photoSuggestionText: "建议准备 6-18 张照片",
    storyHighlights: ["单人笑脸", "成长片段", "毕业寄语"],
    suitableScenes: ["单人毕业照", "成长小册", "竖图记录"],
    pageCount: 10,
    minPhotos: 6,
    priceInCents: 9800,
    coverTone: "#F9D9A8",
    accentTone: "#9BC9EA",
    coverImage: "/assets/templates/graduation-portrait/cover.jpg",
    previewImages: [
      "/assets/templates/graduation-portrait/cover.jpg",
      "/assets/templates/graduation-portrait/page-1.jpg",
      "/assets/templates/graduation-portrait/page-2.jpg",
      "/assets/templates/graduation-portrait/page-3.jpg"
    ]
  },
  {
    id: "graduation-vertical-20",
    slug: "graduation-vertical-20",
    name: "毕业季竖版 20页",
    categoryCode: "graduation",
    categoryName: "毕业纪念",
    summary: "更适合老师寄语、个人成长页和毕业留念，整体更舒展也更温柔。",
    description: "适合想把老师的话、孩子的笑脸和毕业心情一起留住的家庭，翻页节奏会更舒展。",
    themeLabel: "寄语留念",
    badgeText: "寄语更多",
    photoSuggestionText: "建议准备 8-28 张照片",
    storyHighlights: ["老师寄语", "毕业心情", "单人留念"],
    suitableScenes: ["老师寄语", "毕业留念", "个人成长页"],
    pageCount: 20,
    minPhotos: 8,
    priceInCents: 12800,
    coverTone: "#F6DDA8",
    accentTone: "#7AC7D3",
    coverImage: "/assets/templates/graduation-vertical-20/cover.jpg",
    previewImages: [
      "/assets/templates/graduation-vertical-20/cover.jpg",
      "/assets/templates/graduation-vertical-20/page-1.jpg",
      "/assets/templates/graduation-vertical-20/page-2.jpg",
      "/assets/templates/graduation-vertical-20/page-3.jpg"
    ]
  },
  {
    id: "storybook-sample-30",
    slug: "storybook-sample-30",
    name: "毕业故事样册",
    categoryCode: "classroom",
    categoryName: "班级活动",
    summary: "更适合照片比较多的班级，把一天的故事讲得更完整、更有顺序。",
    description: "适合班级照片比较多的时候使用，可以把出发、活动、合照和收尾都串成更完整的一本故事册。",
    themeLabel: "故事长册",
    badgeText: "照片多也适合",
    photoSuggestionText: "建议准备 16-60 张照片",
    storyHighlights: ["活动开场", "班级故事", "一天回顾"],
    suitableScenes: ["春游故事", "班级活动", "照片较多"],
    pageCount: 30,
    minPhotos: 16,
    priceInCents: 18800,
    coverTone: "#A7D9F6",
    accentTone: "#F6B871",
    coverImage: "/assets/templates/storybook-sample-30/cover.jpg",
    previewImages: [
      "/assets/templates/storybook-sample-30/cover.jpg",
      "/assets/templates/storybook-sample-30/page-1.jpg",
      "/assets/templates/storybook-sample-30/page-2.jpg",
      "/assets/templates/storybook-sample-30/page-3.jpg"
    ]
  },
  {
    id: "psd-30-square",
    slug: "psd-30-square",
    name: "清新方版 30页",
    categoryCode: "growth",
    categoryName: "成长记录",
    summary: "适合把成长日常、活动碎片和一家人的喜欢都装进一本清新的小书。",
    description: "适合成长记录和活动合集，翻页时会更像一本轻松、明亮、很适合反复回看的成长纪念册。",
    themeLabel: "清新日常",
    badgeText: "成长合集",
    photoSuggestionText: "建议准备 14-56 张照片",
    storyHighlights: ["成长日常", "活动合集", "一家人喜欢"],
    suitableScenes: ["成长纪念", "活动合集", "照片比较多"],
    pageCount: 30,
    minPhotos: 14,
    priceInCents: 17800,
    coverTone: "#CDE9B8",
    accentTone: "#F3A66E",
    coverImage: "/assets/templates/psd-30-square/cover.jpg",
    previewImages: [
      "/assets/templates/psd-30-square/cover.jpg",
      "/assets/templates/psd-30-square/page-1.jpg",
      "/assets/templates/psd-30-square/page-2.jpg",
      "/assets/templates/psd-30-square/page-3.jpg"
    ]
  }
];
